### PR TITLE
Setup for RTD/Sphinx/ReST

### PR DESCRIPTION
**Pull request by MoltonMontro**
This PR includes all the changes necessary for an initial setup using RTD/Sphinx/ReST. I've minimized the number of content-related changes, and focused on just converting all the files + the initial configuration. **_IIRC the plan is for this to be merged onto a separate branch!_**

Some notes:

1. The "homepage" is **index.rst** (which uses the previous README.md file). We could create a new README to explain the repo specifically.

2. All doc files updated to .RST. The biggest changes had to do with functional limitations/differences between Sphinx, .RST, and .MD. E.g., I had to rename a few sections so they could be linked to. I also created a couple new files, to generate the TOCs for other folders.

3. RTD has been configured similar to my test site. I've included some comments (e.g. in the .readthedocs.yaml file). Warnings will force builds to fail. Downloads for PDF and EPUB are enabled. Sections will automatically generate link anchors usable with `:ref:`. I've stripped the example files.

4. Project information can be found in the conf.py file.

5. File hierarchy currently puts all doc files at `(root) > docs > source`. RTD config files in root, makefile in docs, and docs in source. We could change this though (e.g., moving everything into root?).

6. The docs haven't been organized yet. As such, the TOC currently lists all files alphabetically, and in the repo the doc files are organized identically to how they already were. My current proposition is practically identical to the latest one on my test site, which is:

- Getting Started ("General", "About", etc....)
- Asset Manual (for asset v1 and asset v2 files)
- Mapping (non-asset stuff related to mapping)
- Servers / Programming (server hosting, plugins, misc. docs)
- Maybe an additional section just for data types? E.g., articles like "GUID", "Bitmask", "Asset Pointer", "Master Bundle Asset Pointer"... could add new docs/lists for enums or dictionaries too.

7. `:ref: links/directives haven't been added yet, so all internal links are just relative paths to the .rst file currently. Once the files are organized as desired, I'll update all internal links.

### CODE REVIEW

**Comment by MoltonMontro** [comment]
Regarding bullet num. 6 on organizing the TOC, here's a visual example of that:

image

**Comment by SDGNelson** [comment]
It looks great, thanks!

Re merging and point 5: I think it would be nice for the default branch to still be active considering the .md files need to be kept for the foreseeable future, so perhaps keeping the new files in a subfolder works fine. The game repository's "main" branch is the development branch and the "stable" branch is each actual release, so I think it could work to call the main branch "latest" on the docs site and default to showing the "stable" branch.

If you'd like to go ahead with point 6 organizing then maybe we merge after that?

Some minor requests:

1. Could you restore the editorconfig file please? It looks like it got removed.
2. Could you add a "requirements.txt" in the docs folder with the line "sphinx_rtd_theme" and add 'sphinx_rtd_theme' to the extensions list in conf.py please? I double-checked this locally and it shows a suggestion if the sphinx_rtd_theme module is not installed.

**Comment by MoltonMontro** [comment]
PR organized per <span>#</span>6 (**About**, **Asset Manual**, **Mapping**, **Servers & Programming**, or **Data types**). Files are mostly listed alphabetically in the TOC except for introductory articles. Added `.editorconfig` and added/updates files for Sphinx RTD Theme. Added custom anchors to all docs / some sections, and updated all internal links to `:ref:` directives that use custom anchors. Autosection labels can still be used, but are not currently being used anywhere.

**Note: if the PR is accepted, it'd be preferable to squash the commits into a single commit.**

Here's a couple misc. notes:

- Custom anchor name doesn't matter, but I've tried keeping them predictable. We can put them anywhere, but the anchor will go to the text below it. For example, adding `.. _doc_assets_level:` to the top of .../assets/LevelAsset.rst will place an anchor at the very top of that page. We could link to it with <code>:ref:\`Example text <doc_assets_level>\`</code>.
- Most Sphinx directives require an empty line above and below the directive, along with an empty line between the directive's declaration, and the directive's content itself. Additionally, some inline markup requires a space between the markup and content on either side.
- Nested inline markup isn't a thing with RST/Sphinx. For example, we can't do **_bolded italics_**, nor can we do [`Links in Code`](https://github.com/SmartlyDressedGames/U3-Docs/pull/234). I've already updated any doc files that used nested inline markup.

---

1. Could you clarify about the .md files – e.g., do you want the old .md files on the same branch as the new .rst? If so, I can re-add those and they can sit in _(root)_. My prior understanding was that the current branch would continue to be main for the time being, and this would be a separate one used by RTD.

2. I've noticed some older docs that just redirect to a different doc (e.g. RocketMod → Rocket), or reference removed features like the Devkit / plans for the Devkit. Any thoughts on these? I could just remove them from the RTD docs.

3. Something to consider before accepting PR would be the _file names_. The file names are used for the doc page URL, and are case-sensitive. We currently use **CapitalizedNames** for doc files, but we go with something such as **lowercase-and-hyphenated**. Fake examples below:

- **https://docs.smartlydressedgames.com/en/latest/index.html** (always the same)
- https://docs.smartlydressedgames.com/en/latest/mapping/ManualObjectCulling.html
- https://docs.smartlydressedgames.com/en/latest/assets/ItemAsset/ArrestEndAsset.html
- https://docs.smartlydressedgames.com/en/latest/servers/DedicatedWorkshopUpdateMonitor.html
- **hyphen-ated**
- https://docs.smartlydressedgames.com/en/latest/mapping/manual-object-culling.html
- https://docs.smartlydressedgames.com/en/latest/assets/item-asset/arrest-end-asset.html
- https://docs.smartlydressedgames.com/en/latest/servers/dedicated-workshop-update-monitor.html
- **under_score**
- https://docs.smartlydressedgames.com/en/latest/mapping/manual_object_culling.html
- https://docs.smartlydressedgames.com/en/latest/assets/item_asset/arrest_end_asset.html
- https://docs.smartlydressedgames.com/en/latest/servers/dedicated_workshop_update_monitor.html

**Comment by SDGNelson** [comment]
Looks like the merge is imminent!

1. Yes, let's keep the old .md files around for the meantime. I think this will make it easier for anyone coming into the repo to find the active branch. After RST is merged we can copy-paste a header into the .md files explaining that they are old and the documentation has moved.

2. Sure, now seems look a good time to remove those. The old files were kept in case anyone linked to them.

3. Good point! Considering that they are case sensitive but lowercase with hyphens is fairly standard for the web I agree we should go ahead and rename the files/folders.

**Comment by MoltonMontro** [comment]
PR should be merge ready. (Preferably, squash into a single commit for cleanliness.)

1. Readded the .md files to *(root)*. Once merged, I'll add a note to the top of all the old .md docs, explaining that the documentation has moved. Maybe it should include a mention that the old docs will be removed in the future as well, so players should update any links pointing there?

2. Removed some info/docs that seemed unhelpful. Here's a list of those:
   - Deleted this sentence from `assets/animation`: _"Unturned II's (4.0) rig is significantly more user friendly."_ (U4 isn't relevant to modders right now.)
   - Tweaked `assets/foliage` to note that the Devkit has been removed. (Unsure if the "upgrade" section can be entirely removed.)
   - Tweaked `mapping/landscape` to note that the Devkit has been removed. (Unsure if the doc can be entirely removed.)
   - Deleted `servers/rocketmod`. (Just a redirect to **servers/rocket**.)

3. Renamed files/directories to be **lowercase-and-hyphenated**. I've updated some anchors/links as well, to better reflect the revised filenames. I've also made the H1 headings and filenames for all assets consistent.

**Comment by MoltonMontro** [comment]
@SDGNelson Bumping as this PR is still merge ready (assuming everything looks good for you locally – it builds correctly on my test RTD site).

**Comment by SDGNelson** [comment]
Awesome! Sorry, I missed your most recent comment. Here we go!

**Pull request merged**
