### PR TITLE
Added Bypass_ID_Limit to Items

### PR DESCRIPTION
**Pull request by Ongjming**
Added that to Items as it can be used on items as well (Maybe even more stuff like objects/effects etc. for total conversion mods purposes)

First time adding things in after the references and tables are added. Do tell me if I missed out on something.

### CODE REVIEW

**Comment by MoltonMontro** [comment]
Looks good to me & the PR builds correctly; thanks! Only (minor) nitpick is that the heading markup doesn't need to be longer than the length of heading text.

```rst
Bypass_ID_Limit :ref:`flag <doc_data_flag>`
:::::::::::::::::::::::::::::::::::::::::::
```

**Comment by SDGNelson** [comment]
Thanks for the submission! And thanks for your edit note Molt!

It might not have been documented because it was only used for the curated content that was included in the base game for a time, but I suppose it should be covered. I'd advise against using it without good reason, however. Hopefully someday all the legacy ID stuff is behind us.

If you'd be willing to change the target branch from `stable` to `latest` and edit the line length as mentioned by Molt then I'll merge the PR.

**Comment by Ongjming** [comment]
Thanks, am new to all this so really appreciate the explanation on how they work.
How do I change the target branch? I will come back to explore more tomorrow around 18 hours or so later from now.

Edit: Yay I found it! (From this page https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request and a bit of clicking)

**Comment by SDGNelson** [comment]
Perfect, thanks!

**Pull request merged**
