### PR TITLE
Create CommandLine.md

### PR DESCRIPTION
**Pull request by MoltonMontro**
Contains a majority of the command-line arguments available to players. Although the majority of the arguments documented are for the Unturned game, the documentation also includes arguments that are primarily intended for servers or hosting services, and some common Unity commands.

The commands are sorted alphabetically, ignoring case. However, we could instead choose to break this up into two or three sections. One for the Unturned game, one for the Unturned Dedicated Server app, and one for common Unity command-line arguments.

### CODE REVIEW

**Comment by SDGNelson** [comment]
I have been hesitant to do this, but I do know there have been requests. Agreed that it would make sense to split into two sections: one for relevant/useful Unity options, one for game options.

You listed force-d3d11-bltblt-mode=, but does Unity actually support that as a command-line arg?

I do not think these should be included because they are either no longer supported or should not accidentally be used:
-AggressiveGC
-ConstNetEvents
-SNS_AllowWithoutAuth

-w and -h are aliased because of Steam support articles that players seem to find. Unity's -screen-width, -screen-height, -screen-fullscreen, and -window-mode take priority because of the Unity player launcher when holding alt.

**Comment by MoltonMontro** [comment]
I was unable to find a reference to **force-d3d11-bltblt-mode=** in Unity's documentation, but it is referenced in your [Troubleshooting.md](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Troubleshooting.md) file.

**Comment by MoltonMontro** [comment]
What is your suggestion regarding documenting in-game resolution options – do you believe Unity's **-screen-width**, **-screen-height**, **-screen-fullscreen**, and **-window-mode** options be mentioned? Or are you just commenting on the accuracy of the sentence, and if so is their a more accurate statement:
> Unity's built-in command-line arguments take priority over _Unturned_'s equivalents.

(Also: I've split the file into two subheadings. One for game options, one for useful Unity args.)

**Comment by SDGNelson** [comment]
Looks good, thanks! SNS_AllowWithoutAuth should not be accidentally used because it was for trying to work around the openssl bug, AggressiveGC was kind of a dumb setting to see how much extra memory got reclaimed during loading assets, and ConstNetEvents does not matter after the RPC rewrite.

**Pull request merged**
