### PR TITLE
Clarify default app install directory

### PR DESCRIPTION
**Pull request by MoltonMontro**
Last year, #219 proposed updating the Server Hosting page to mention `force_install_dir`. They didn't sign the Contributor License Agreement, but I've made a similar commit in this PR.

- https://unturned--320.org.readthedocs.build/en/320/servers/server-hosting.html#doc-server-hosting-install-with-steamcmd

I think we can close the other PR if this one is accepted.

### CODE REVIEW

**Comment by SDGNelson** [comment]
Good idea to catch up on old stuff. Occasionally there are reports of issues with different install directories, however, particularly with finding the steam redist files IIRC. I'm not sure if we should recommend it in the docs without a *reason* for suggesting it. Or maybe a separate article about why it's worth using and how to use it, similar to Fake IP? As-is I think it's kind of a "your miles may vary" feature of steamcmd that we don't necessarily need to support.

**Comment by MoltonMontro** [comment]
If the issue mentioned in #219 isn't common enough to warrant a full step, maybe we mention the default install path in the `app_update` step (with a link back to SteamCMD's documentation for changing this path)

**Comment by SDGNelson** [comment]
Sure, that sounds reasonable to me.

**Comment by MoltonMontro** [comment]
Alright, I've changed this to just add a bit more emphasis to how server files are downloaded to the default app install directory (w/ a link back to the SteamCMD section that mentions changing this).

Fixes some styling error in other steps (some lists were misformatted and used 4-space indents instead of 3).

**Comment by SDGNelson** [comment]
Thanks, that looks like a good way to include the information.

Regarding spaces: Does RST have a recommended style guide suggesting 3 spaces for indentation? The .editorconfig file right now is set to 4 spaces but default tabs. (we can override for RST file type if needed) Which editor are you using?

**Comment by SDGNelson** [comment]
(for others reading, 3 spaces was actually to prevent bolding of list items)

**Pull request merged**
