### PR TITLE
Vehicle asset data pull request

### PR DESCRIPTION
**Pull request by Kopfstroh**
I decided to document all the Vehicle .dat options I could find. 
I'm not sure if its 100% all or if I mentioned anything obsolete or outdated. 
It might make sense to split this into several files and have it have its own folder with all the properties seperately.

Areas that I didn't know enough about, so maybe you could add some information:
Trains (specifically the offset options),
Shared_Skin_Name,
SqrDelta,
Stamina_Boost

English is not my first language, so it may have some spelling mistakes or grammatical/punctuation mistakes.

### CODE REVIEW

**Comment by MoltonMontro** [comment]
As per the status checks on this PR, your pull request failed to build correctly on the documentation site (due to 4 warnings that need to be corrected). I've copy-pasted the relevant part of the errors below:

```
/home/docs/checkouts/readthedocs.org/user_builds/unturned/checkouts/282/assets/vehicle-assets.rst:5: WARNING: Title underline too short.

Vehicle Asset Properties
---------------------
/home/docs/checkouts/readthedocs.org/user_builds/unturned/checkouts/282/assets/vehicle-assets.rst:175: WARNING: Title underline too short.

Miscellanious Properties
---------------------
/home/docs/checkouts/readthedocs.org/user_builds/unturned/checkouts/282/assets/vehicle-assets.rst:175: WARNING: Title underline too short.

Miscellanious Properties
---------------------
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/unturned/checkouts/282/assets/vehicle-assets.rst: WARNING: document isn't included in any toctree
```

- Can you rename the file to `vehicle-asset.rst` instead of `vehicle-assets.rst`? This would be more in line with the naming of other asset docs.
- 3 warnings are syntax issues. Please fix the title underline length. Title underlines should at least be the same length as the title. (It cannot be less.)
- 1 warning is a missing document. All documents must be included in the Table of Contents. Please add the document to `index.rst` in root.
- I've noticed a couple typos. E.g. `Miscellanious` → `Miscellaneous`, `wether` → `whether`, and `Maxiumum` → `Maximum`.

**Comment by Kopfstroh** [comment]
image
I added the assets/vehicle-asset above assets/vehicle-physics-profile-asset just like it is in the alphabetical order in the asset folder, do I need some kind of special permissions to make changes to index.rst?

**Comment by MoltonMontro** [comment]
Thank you for updating the PR per my requests. It looks like the current version builds correctly.
image

**Comment by MoltonMontro** [comment]
@SDGNelson I think the current version of this PR by Kopfstroh is fine to merge if you don't have any concerns with it. The documentation is incomplete, but a disclaimer can just be added to the top and/or it can just be finished in a separate PR.

**Comment by SDGNelson** [comment]
First of all, thanks for the contribution!
Unfortunately I think Molt or I should finalize it before merging because there might be some inaccuracies, for example `Train_Car_Length` is actually how far apart the train cars are spaced on the tracks. For the most part it seems to be accurate though!

**Comment by MoltonMontro** [comment]
Replying here to note that I'll go through this to double-check the info / I am already going through this.

**Comment by SDGNelson** [comment]
Closing now that vehicle docs have been merged (#284)

**Pull request closed without merging**
