### PR TITLE
Revise how Docs are organized.

### PR DESCRIPTION
**Pull request by MoltonMontro**
Ended up squeezing a lot of changes into a single PR, sorry. :/ **Shouldn't be merged yet.** Some page links will change once merged, and I don't think I like this setup just yet.

1. Pages split into 3 new TOC sections (replacing "Asset Manual"). Not happy with how some of these. Mostly with "Creating Objects and NPCs". Maybe NPC Logic (everything except the actual object NPCs) should be split from Objects? Also looking at Blueprints, Actions, CharacterMeshReplacement... There's at least 3 Vehicle-related docs that could be grouped together. Lot of level-related assets, technically. 🤔

2. Unknown pages now show a **404 Not Found** message.

3. TOC sections are now collapsible! You can find the script/styling in ``_static``.

4. Rewrote the "Upgrading Unity Version" page.

### Minor Stuff

- Renamed "Miscellaneous"section to "SDG / Project Info". Maybe there's a better name? Source Documentation? Project Info? Unsure... All feel kinda ambiguous or misleading.
- Listed the Unity modules required for multi-platform support.
- Updated descriptions for ``Asset_Bundle_Version``, ``this``, and ``Bypass_Claim``.
- Fixed a bug w/ RTD Sphinx Theme. (Unreadable select version text in sidebar.) Should be _officially_ fixed in the next RTD Sphinx Theme version.

### CODE REVIEW

**Comment by MoltonMontro** [comment]
Merge conflicts. 🤔 I assume it's hung up on https://github.com/SmartlyDressedGames/Unturned-Docs/commit/5e86cb0161953b461b3a7a6be8078b53e61d09ee and https://github.com/SmartlyDressedGames/Unturned-Docs/commit/0c096cbe76213434ce1fafbf6e8c86dec9d7712e

**Comment by SDGNelson** [comment]
Looking good so far! Definitely more readable in the left sidebar now :)

**Comment by MoltonMontro** [comment]
3.x repo let me fix the merge conflicts within the PR. Not sure why it doesn't let me do so here - maybe it's confused because of path changes. :/

Will go through manually and see what's wrong.

**Comment by SDGNelson** [comment]
Apparently it's too complex :[
7U1A08xwce

**Pull request merged**
