### PR TITLE
Update trap-asset.rst

### PR DESCRIPTION
**Pull request by Spebby**
added Range2 and Trap_Cooldown properties.

### CODE REVIEW

**Review by SDGNelson — CHANGES_REQUESTED** [review]
Thanks for the submission! Very minor but could you change the ';' to ':' please?

**Comment by MoltonMontro** [comment]
Please add a blank newline between each property as well, so they format properly. Without a blank newline, they'll all appear on the same line.

**Comment by Spebby** [comment]
Sorry about going dark: I didn't get a notification from github. I'm pretty new to pull rq's so _I think_ I made the changes. Also had to sync my branch with the main. I think this rq pre-dates the stable/latest branches rule, in the future will pull that branch.  Will read up on how to properly pull rq before my next request.

**Comment by MoltonMontro** [comment]
Yeah, the changes look fine. Thanks! @SDGNelson can manually change the branch for the pull request.

**Pull request merged**
