### PR TITLE
Allow_Placement_Inside_Clip_Volumes

### PR DESCRIPTION
**Pull request by MoltonMontro**
Just making a note of it.

### CODE REVIEW

**Comment by SDGNelson** [comment]
Thanks!

**Comment by Ongjming** [comment]
While searching for this term I came across this post, wanted to ask:
What exactly does it do? Does having this tag line allow the item to be placed into other item's colliders? Or does it allow other items to be placeable within this item's colliders?

**Comment by SDGNelson** [comment]
@Ongjming some maps have placed Player Clip volumes with Block Player disabled as a way of preventing item building, and this option bypasses that prevention.

**Comment by Ongjming** [comment]
> @Ongjming some maps have placed Player Clip volumes with Block Player disabled as a way of preventing item building, and this option bypasses that prevention.

Thank you so much for the reply and helping me understand this better!
Cheers! :)

**Pull request merged**
