### PR TITLE
Update conf.py due to deprecation of Sphinx context injection at build time

### PR DESCRIPTION
**Pull request by MoltonMontro**
Tentative fix per https://about.readthedocs.com/blog/2024/07/addons-by-default/.

~~We probably won't need to do anything else as part of the migration to RTD Addons.~~

These GH issues are both somewhat relevant:
- [Deprecations: list of all past and ongoing deprecations](https://www.github.com/readthedocs/readthedocs.org/issues/10587)
- https://github.com/readthedocs/readthedocs.org/issues/11474

### CODE REVIEW

**Comment by MoltonMontro** [comment]
@SDGNelson RTD Addons will eventually be enabled for all projects by default on October 7th. We can enable addons now though, and make sure everything is working. https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons

**Comment by humitos** [comment]
@MoltonMontro I can enable the `DISABLE_SPHINX_MANIPUALTION` feature flag in your project if you want to perform the tests. That flag, together with [enabling Read the Docs Addons manually](https://docs.readthedocs.io/page/addons.html#enabling-read-the-docs-addons) emulates the default future behavior. Let me know.

**Comment by SDGNelson** [comment]
I've now enabled addons for the Unturned project. 👍 

We're big fans of RTD, thanks for reaching out @humitos! Sure, I think we'd be up to test with Sphinx manipulation disabled. What do you think Molt?

**Comment by MoltonMontro** [comment]
> @MoltonMontro I can enable the `DISABLE_SPHINX_MANIPUALTION` feature flag in your project if you want to perform the tests. That flag, together with [enabling Read the Docs Addons manually](https://docs.readthedocs.io/page/addons.html#enabling-read-the-docs-addons) emulates the default future behavior. Let me know.

@humitos Sure! If you could enable that flag, we'd appreciate it. :)

**Comment by humitos** [comment]
> @humitos Sure! If you could enable that flag, we'd appreciate it. :)

Cool! I enabled the flag in the `unturned` project. Let me know if everything works as expected. I'd really appreciate any feedback you may have 👍🏼

**Pull request merged**
